name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
          
      - name: Test Project
        run: ./gradlew clean tests:test
        
      - name: Archive Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: tests/build/reports/tests/test
          
      - name: Deploy Test Report
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages 
          folder: tests/build/reports/tests/test
          commit-message: 'Deployed from RUNID-${{github.run_id}}'
          target-folder: docs/report
